# Generated by Django 2.2.7 on 2019-11-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191114_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=' ', max_length=70),
            preserve_default=False,
        ),
    ]
