# Generated by Django 2.2.7 on 2019-11-11 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23)),
                ('new_price', models.FloatField()),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('for_who', models.CharField(choices=[('M', 'men'), ('W', 'women'), ('A', 'accessories')], max_length=1)),
                ('category', models.CharField(choices=[('S', 'shirt'), ('D', 'dress'), ('J', 'Jacket'), ('T', 'trouser'), ('B', 'boot'), ('A', 'accessoriess')], max_length=1)),
                ('stock', models.IntegerField()),
                ('new_arrival', models.BooleanField()),
                ('size', models.CharField(max_length=23)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.CharField(max_length=23)),
                ('quality_checking', models.CharField(choices=[('YES', 'YES'), ('No', 'NO')], max_length=3)),
                ('code', models.CharField(max_length=23, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
