# Generated by Django 2.2.7 on 2019-11-12 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_itemoreder_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOreder',
            new_name='OrederItem',
        ),
    ]
