# Generated by Django 2.2.7 on 2019-11-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191113_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobail_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobail_number', to='main.Address'),
        ),
    ]
