# Generated by Django 2.2.7 on 2019-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191113_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mobail_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
