# Generated by Django 2.2.7 on 2019-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191115_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=235)),
                ('opened', models.BooleanField(default=False)),
            ],
        ),
    ]
